# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3aae3016862f718a8dfc7c5e5de2357a66c1477fb3052d1e007a515747ee59e921273306e49cc6ce4a18cd3261dc45cd11b48be46dd322e714e09542b350452

test:
  secret_key_base: fd2a9dfad4f0ab379ad919f6baf38f33e51b54873ceca5f28de8a80d0adecc9d1e0b8510ba5e32b503d59e31602b810eb02721bceb92f83d8299f5caf3e522f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
